### ISSUE TITLE
Labs are not linked together when stacked

### ISSUE THREAD

**Issue by hubastard** [hubastard/nebula#111]
During our playthrough:

1. Client create and stack research labs
2. Client set the bottom lab recipes
3. Host only have the recipes set for the bottom lab the other one on top are not linked together

![labs](https://user-images.githubusercontent.com/69216913/114110880-8e0ad600-98a6-11eb-9567-993db944f241.PNG)

**Comment by Baldie-dev** [comment]
Checking it now :)

**Comment by Baldie-dev** [comment]
![image](https://user-images.githubusercontent.com/79051050/114200845-e351f080-9955-11eb-88b4-56b5e5dc421d.png)

Solved, closing
