### ISSUE TITLE
Building recipes not synced if copy pasted

### ISSUE THREAD

**Issue by hubastard** [hubastard/nebula#113]
When the client or host copy paste the recipe on another building, it is not synced properly on remote players.

Client State:
![client building](https://user-images.githubusercontent.com/69216913/114111830-f490f380-98a8-11eb-82d4-e42a431351d5.PNG)

Host State:
![nothing](https://user-images.githubusercontent.com/69216913/114111847-02df0f80-98a9-11eb-9617-87171430a79b.PNG)

**Comment by Baldie-dev** [comment]
checking it now

**Comment by hubastard** [comment]
Verified, working.
