### ISSUE TITLE
Clients items are not removed from their inventory when they build

### ISSUE THREAD

**Issue by hubastard** [hubastard/nebula#114]
When a **client** builds an entity, the item is not substracted from their inventories.

**Comment by hubastard** [comment]
@Baldie-dev Maybe the transpiler is not working properly

**Comment by Baldie-dev** [comment]
ooh right, I know!

Clients are never calling BuildPrebuilds by themself, they are always waiting for the packet from the server, so they thinks that they are not the builders.

**Comment by sp00ktober** [comment]
Then it should be easy, just remove the item from inventory manually :)
