### ISSUE TITLE
Host should automatically save on quit

### ISSUE THREAD

**Issue by hubastard** [hubastard/nebula#117]
During our playthrough, it looked like as if the host did not saved automatically when quitting from the esc menu.

**Comment by Baldie-dev** [comment]
On the exit from main menu, the `SimulatedWorld.Initiliazed` is already false, so the save was not triggered:
```cs
if (SimulatedWorld.Initialized && LocalPlayer.IsMasterClient)
{
SaveManager.SaveServerData(saveName);
}
```

fix is on the way.
