### ISSUE TITLE
Clients should not be able to save or autosave

### ISSUE THREAD

**Issue by hubastard** [hubastard/nebula#118]
Right now after playing a multiplayer game as a client. When they click on continue to continue a single player game, it loads the previous multiplayer game. 

We should prevent saving the game if you're a client.

**Comment by Baldie-dev** [comment]
I thought that It was part of my commit, hmmm. Maybe I missed something:
https://github.com/hubastard/nebula/blob/master/NebulaPatcher/Patches/Dynamic/GameSave_Patch.cs

**Comment by Baldie-dev** [comment]
This will be in my next PR, since I have to solve it to get rid of annoying errors :/

**Comment by hubastard** [comment]
@Baldie-dev Maybe your patch doesn't work because you have 2 prefix that are not returning a boolean.

**Comment by Baldie-dev** [comment]
Fixed in the last PR :)

**Comment by hubastard** [comment]
Looks good
