### ISSUE TITLE
Clients are able to duplicate buildings by destroying their prebuild with a double click.

### ISSUE THREAD

**Issue by hubastard** [hubastard/nebula#127]
At first I had 7 labs and by double clicking the prebuild while in destroy mode, it calls the destroy function twice on the client and duplicated the item.

https://user-images.githubusercontent.com/69216913/114275291-f6b19a00-99ef-11eb-8e2c-689989074048.mp4

**Comment by Baldie-dev** [comment]
Bug fix in progress :)

**Comment by Baldie-dev** [comment]
retested and does not happens now.
