### ISSUE TITLE
Coal appearing out of nowhere

### ISSUE THREAD

**Issue by fudgey297** [hubastard/nebula#150]
![image](https://user-images.githubusercontent.com/29759060/114940426-ba3fcd00-9e39-11eb-84b4-e80d10e21cec.png)
The top image is of the original player

![image](https://user-images.githubusercontent.com/29759060/114940472-cb88d980-9e39-11eb-974c-eb8f1bea365f.png)
Bottom image is of our third player

For the first two players to join the game, coal was literally appearing on the conveyor out of nowhere, whereas for the third player it was perfect. This was completely random, we had not done anything to create this other than connect smelters that were making iron ingots to the conveyors, as you can see in the images. This was fixed by replacing the conveyors and we still don't have a clue what happened

**Comment by Baldie-dev** [comment]
maybe the #172 fixes this, lets see if this happens again.

**Comment by sp00ktober** [comment]
Closed because its most likely the same issue as #336
