### ISSUE TITLE
Progress of clients reset after second time joining.

### ISSUE THREAD

**Issue by TahoeBennie** [hubastard/nebula#152]
I come back to the world I have played with my friend, joined for the second time, and I notice a few things:
My inventory is reset, my color is different, and I do not have any research upgrades (example: cannot fly anymore)
Proof that its reset:
My power (client)
![image](https://user-images.githubusercontent.com/77897972/114953000-4a671d80-9e0c-11eb-9634-db296c003214.png)
My friend's power (host)
![image](https://user-images.githubusercontent.com/77897972/114953025-581ca300-9e0c-11eb-9222-9bc28daf58ec.png)

**Comment by TahoeBennie** [comment]
Wait nvm fount the fix, clients also have to load their save game of lastexit.

**Comment by hubastard** [comment]
Reopen, client should not have to load a safe to get their game state

**Comment by hubastard** [comment]
I've done some fixes to prevent clients from being able to save the game and load it in single player.
But the bug where the client is reset and doesn't have the same tech bonuses as the host I should can't replicate it. @Baldie-dev  do you have some ideas?
