### ISSUE TITLE
Ghost items

### ISSUE THREAD

**Issue by azergh** [hubastard/nebula#156]
So, me and my friend are playing through using the mod. There's only 2 players, and occasionally items that my friend deletes from conveyors will go into my inventory. I put the items I received onto a conveyor and my friend says he can't see the item.
My game (client):
![image](https://user-images.githubusercontent.com/46851962/115036132-24518400-9ec5-11eb-934e-3431935cffdc.png)
My friends game (host):
![image](https://user-images.githubusercontent.com/46851962/115036199-34696380-9ec5-11eb-8f76-70fd208675b7.png)

I genuinely don't know what would've cause this so, good luck I guess Baldy :) (and everyone else ofc)

**Comment by Baldie-dev** [comment]
oooh, I did not know that you can put stuff on the belts :D
