### ISSUE TITLE
Item Desync

### ISSUE THREAD

**Issue by azergh** [hubastard/nebula#158]
Me again, my friend and I also noticed some item desync. On my friends screen this conveyor had nearly no iron ingots on the line, whereas on mine it was full.
The furnaces we used to smelt were out of sync from what I can see since 2/4 of the smelters were full with iron, and my friend says there was no iron in any of them.
My game (client): 
![image](https://user-images.githubusercontent.com/46851962/115037073-00db0900-9ec6-11eb-88d2-6aa801040088.png)
My friends game (host): 
![image](https://user-images.githubusercontent.com/46851962/115037138-105a5200-9ec6-11eb-9b20-c3655bb2744e.png)

**Comment by Baldie-dev** [comment]
Maybe the #172 will fix this, so let see if this happens again.

**Comment by hubastard** [comment]
Seems fixed
