### ISSUE TITLE
Tech bonuses not synced (even after connecting twice)

### ISSUE THREAD

**Issue by azergh** [hubastard/nebula#159]
There's an issue right now where joining into a game will reset all of your research/tech bonuses. Upon disconnecting and reconnecting, you will gain some but not all of your bonuses when you are in the game. I was able to regain my flight and my higher energy capacity, however I still did not gain the greater inventory space that we unlocked previously.
My game (client):
![image](https://user-images.githubusercontent.com/46851962/115045164-29670100-9ece-11eb-84e0-523b99fc6d5a.png)
![image](https://user-images.githubusercontent.com/46851962/115045179-2d931e80-9ece-11eb-8bc5-c377110502cd.png)

My friends game (host): 
![image](https://user-images.githubusercontent.com/46851962/115059616-b0bc7080-9ede-11eb-958e-eba3b388ea4c.png)

**Comment by Baldie-dev** [comment]
This bug is about not syncing inventory size during the mecha upgrade sync. I will fix it.
