### ISSUE TITLE
Vegetables needs to be mined twice on remote planets

### ISSUE THREAD

**Issue by Baldie-dev** [hubastard/nebula#164]
On the remote planet, players need to mine vegetables twice in order to destroy it. They are probably generated twice.

[youtube](https://www.youtube.com/watch?v=rabfVCWFIH8)

**Comment by Baldie-dev** [comment]
I am on it

**Comment by UeliDeSchwert** [comment]
Just a note: You sure you mean "Vegetables", not "Vegetation"? 😆
