### ISSUE TITLE
Multiple Players using Wireless Power tower does not increase power usage

### ISSUE THREAD

**Issue by jadrian2006** [hubastard/nebula#175]
Build: 824e8cd
When multiple players use the wireless power towers to charge mech, there is no increase in power. 

Replicate: have client stand under wireless power.
Have 2nd player move in and out, power consumption values do not change.

**Comment by Baldie-dev** [comment]
Yeah, power system synchronization is not implemented yet. This could be future enhancement :)

**Comment by milesvdw** [comment]
Quite a few issues with this actually, for example:
when one player is charging, another walks up to start charging, and first player leaves, second player's mech stops charging unless they leave wireless tower range and re-enter
