### ISSUE TITLE
Research Desync - Manual Resarch

### ISSUE THREAD

**Issue by Shad0wlife** [hubastard/nebula#183]
We managed to desync our research progress by having a starter level research that requires 2 types of items, with one player having one of the items in the inventory and another player having the other item type. For the client, the research disappeared from the queue, and afterwards the queue stayed desynced while any research was still in it.

I removed the research as well, and even when he readded it, it did not reappear for me, and his research labs were researching different tech than mine.

Maybe implement some kind of item management, to sync the items already "eaten" by inventory research?

**Comment by Baldie-dev** [comment]
I tried this:
One player has one item inside and the second player has the second item inside:
![image](https://user-images.githubusercontent.com/79051050/115141064-bb8c1800-a03a-11eb-9459-7d520ae843ab.png)

@Shad0wlife: `For the client, the research disappeared from the queue,` - how this happened? Did it disappear on its own?

If I remove it from one player, it also gets removed from the second one:
![output](https://user-images.githubusercontent.com/79051050/115141122-ff7f1d00-a03a-11eb-99d9-3bd7dbd4ca6f.gif)

I can do the implementation of the "eaten" items, but I am not sure about that research desync, which troubles me. 

If I queue it again, the items are still present:
![output](https://user-images.githubusercontent.com/79051050/115141207-571d8880-a03b-11eb-8fa6-df06175eee95.gif)

**Comment by Shad0wlife** [comment]
Hmm.

The exact procedure was:
One research using blue cubes in the research building was in progress. The research that bugged was in the queue and another blue research building in the queue after that.
When the first research finished, the second research (specifically the mech upgrade that requires steel, I don't remember which one it is exactly) ate the steel from my friend and the circuit boards from me. It then disappeared from him (the steel is gone) and just went to the next queued tech while for me that research still waited for the steel.
When I then dequeued the research, the next one went in line and showed the circuit boards in the panel as added, but no info about needed (so usually it says x/y, but there it only showed x). Because the research after the bugged one started earlier and in the research building using cubes for the client, we were desynced.

**Comment by Shad0wlife** [comment]
Additional info: something like this where the client forgot the host queue happened twice with research from lab buildings now as well.
Will investigate further.

**Comment by Baldie-dev** [comment]
We have also experienced that issue.  The most confusing thing is, that queue is synchronized between all clients (all clients can see same thing), but it is different only on the host :D

**Comment by Shad0wlife** [comment]
Idea: the host does not process UnlockTech Packets...
But the clients do. What if the tech finished naturally for the clients, and then they get the packet as well which dequeues the next tech. Starting then it is desynced and won't resync automatically anymore.
Or is finishing techs disabled via transpiler for clients?

**Comment by Baldie-dev** [comment]
https://github.com/hubastard/nebula/blob/master/NebulaPatcher/Patches/Dynamic/GameHistoryData_Patch.cs

The client should completely ignore the methods and execute them only if a packet from the server is received:

- DequeueTech
- GainTechAwards
- UnlockRecipe
- UnlockTechFunction
- AddTechHash

But maybe I missed something.

**Comment by Shad0wlife** [comment]
Maybe you did actually forget something.
The UnlockTech function is not prefixed I think.
Of course that effectively also calls the UnlockRecipe, UnlockTechFunction and GainTechAwards, but maybe something in UnlockTech makes the difference?

Or maybe the isIncomingrequest is somehow set to true for the prefix and it allows the game's run and the packet's run?

**Comment by Baldie-dev** [comment]
I see the issue. The host cannot send to the clients just the changes, but the final result (full queue).

**Comment by Baldie-dev** [comment]
- Sometime there is some desync on the clients (all clients see same research queue, but it is different than what host see). This seems to happen when some research finishes.
- Sometimes client see some research as completed, even though it is not completed.
- Sometimes, if the research consumes your items from inventory, and somebody changes the research your items are gone.
+ one improvement is needed: Sending regular updates (maybe every 2 sec) to sync number of consumed cubes. So all players will see the same number in the research UI.
I am currently syncing the total number of hashes in the research by: GameHistoryResearchUpdatePacket. But it is probably not enough, we need sync also number of required cubes for the research.
maybe another bug:
- when we tested it yesterday, the research for some reason went waay to fast. It was consuming cubes with much higher speed that it should :smile:
+ One necessary improvement, instead of sending packet: "Remove tech in queue at position x" it should be: "Remove tech with ID x from queue".
