### ISSUE TITLE
Add support of the `Log` class in the server code also to have the same API everywhere.

### ISSUE THREAD

**Issue by hubastard** [hubastard/nebula#19]

**Comment by Flapperkewiet** [comment]
I'll fix this.

Do you want to use just a simple file stream or did you have another idea in mind?

**Comment by hubastard** [comment]
Since I'll be refactoring the projects to include the server code into the client code, this won't be an issue anymore. Since we will be able to use the Log class now into the server code. I'll add you to my refactor PR to let you know once it is done so you know when the solution will be ready to start the working more massively on the synchronization code.

Nice job for the color btw I tested it it's nice :)
