### ISSUE TITLE
3 Players wrong animation and invisible player

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#199]
https://user-images.githubusercontent.com/79335616/115384901-d8aa1d80-a1d7-11eb-9e2e-587b3ca7911c.mp4

[a_Station_Test2.zip](https://github.com/hubastard/nebula/files/6342937/a_Station_Test2.zip)

top left - host
top right - player 2
bottom - player 3

As you can see, player 2 cant see player 3 and player 3 sees player 2 as player 3 (name tag).
also host applies animations from player 2 to player 3

This was tested on my branch but merged with current master. Maybe someone could confirm this?

**Comment by Mushroom** [comment]
I could not reproduce this issue (see atached screenshot)
![image](https://user-images.githubusercontent.com/397696/115427049-02277100-a1f9-11eb-901d-5f1c808537a0.png)

**Comment by Mushroom** [comment]
![image](https://user-images.githubusercontent.com/397696/115428021-e2dd1380-a1f9-11eb-8105-dc7e4f7ee80e.png)

**Comment by sp00ktober** [comment]
Thats so weird, then it must be some of my ILS code causing this..
I will need to search for the cause once the rest of it is done.

**Comment by sp00ktober** [comment]
Seems to only happen for me for some reason, so im closing this for now.
