### ISSUE TITLE
Reconnecting to non-existing server not caught

### ISSUE THREAD

**Issue by pGlase** [hubastard/nebula#203]
I think this is a minor issue, but I'm not quite sure how to best approach this.

Steps to reproduce:
1. Open (local) server and join it
2. Server closes -> Client will recieve notification that server is unavaliable(OK)
3. Client selects reconnect, which will fail due to timeout
4. Client enjoys a twilight version of the server state for themselves:
![grafik](https://user-images.githubusercontent.com/60819856/115596866-df6c8980-a2d8-11eb-8d19-c72d9de6dabf.png)

I'm not entirely sure if we can fix this in a "nice" way - The menu is afaik a simulated world, which is replaced on joining.
I think of two possible solutions:
A) reloading the main menu 'world' (overlayCanvas?) or 
B) simply exit the application/trigger an exception for stack trace.

**Comment by Baldie-dev** [comment]
I think this is same issue as #131 . So I will close that issue and leave this one :)

**Comment by hubastard** [comment]
Thanks for the repro steps, I'm looking at this issue now.
