### ISSUE TITLE
GameTick synchronization

### ISSUE THREAD

**Issue by Baldie-dev** [hubastard/nebula#210]
Since game tick can go slower on the host (due to the CPU demands), we could maybe improve the GameTick sync on the clients:
If the client's game tick is lower, it would manually trigger extra ones. If the client's game tick is higher, it would skip the next "x" game ticks.

Thoughts?

**Comment by Therzok** [comment]
Yeah, I suggested this since the simulation is pretty deterministic. This would go in well in checksummed and partial resyncs on components.

**Comment by sp00ktober** [comment]
implemented by bullettime
