### ISSUE TITLE
Error and conflict in deleted entities

### ISSUE THREAD

**Issue by Rinine** [hubastard/nebula#222]
I, as the host, deleted a belt with shift + click.
In doing so, I also deleted my friend's smelter that he was building (away from me, no connection to the belt)

Also that produced desynchronization. Since I saw the smelter of him built, but he did not see it (in fact he could walk through because for him it did not exist) 

mod version v0.0.2.0

**Comment by Baldie-dev** [comment]
checking it now.

**Comment by hubastard** [comment]
Since the 0.7.x patch the behaviour changed a lot, I will close this because I don't think it is relevant anymore. Open it back if you it happen again.
