### ISSUE TITLE
Console error and infinite item collection

### ISSUE THREAD

**Issue by Rinine** [hubastard/nebula#223]
Steps to reproduce (happen 100% of the time)

Enter game, load my single player savefile to play single player ("load game" menu from main menu, not from multiplayer menu)
Right click in a stone, console error and collect infinite stone?

![b1tamtf](https://user-images.githubusercontent.com/83186910/116009932-6775ca80-a61c-11eb-9361-724bebb854ba.png)

I can't continue my single player worlds if the multiplayer mod is installed?

Note: I have ILS and PLS built in my single player save file

**Comment by sp00ktober** [comment]
@Rinine could you somehow privide me your save file and also tell me which version of the mod you used?
I just tested on current master branch and could not reproduce it, maybe its already fixed.

**Comment by Rinine** [comment]
Sure, savefile: https://dl.dropboxusercontent.com/s/kmkp81essrlq1o2/World%202.dsv

Mod version is v0.0.2.0 the latest pre-release

**Comment by sp00ktober** [comment]
Thanks for the save and info, i think we already fixed this in the master branch as i cannot reproduce this with my saves, your save or a new game. Neither in multi nor in singleplayer.

Maybe you try it with [the latest build](https://github.com/hubastard/nebula/actions) and see (after making a backup of your save just in case) if it fixes the issue for you?

**Comment by Rinine** [comment]
Confirmed, works with no issues with that build =D

**Comment by sp00ktober** [comment]
Thats cool :)
