### ISSUE TITLE
ILS wrong remoteOrder value

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#230]
For most of the time the value is correctly displayed (the indication of items that are in transfer). It is also updated to the correct one when the ILS UI is closed and opened again.
But the value is wrong atleast in the following situation:

- ILS on planet A (has ships)
- ILS on planet B (has no ships or none that would pick up work for this)
- ILS on planet A demands items from ILS on planet B
- ILS on planet B indicates correctly how mayn items will be taken out of inventory while ships travel to planet B
- once ships take out the items of ILS on planet B the remoteOrder value does not get updated

**Comment by sp00ktober** [comment]
Im not too sure if this is still an issue as the underlying code did change quite a bit in our latest updates.

**Comment by starfi5h** [comment]
It should be good now? If there are still problems feel free to reopen the issue.
