### ISSUE TITLE
Have a way to log all broadcasted packets on each game instance

### ISSUE THREAD

**Issue by Therzok** [hubastard/nebula#246]

**Comment by pGlase** [comment]
If you haven't already started work on this, i'd like to try to figure something out.
I'm thinking about creating a seperate logfile for this, so that we don't clutter up the regular bepinex output.

**Comment by Therzok** [comment]
Yup, I wanted to save the actual Network packet data to disk and have some tool to decode it to json or whatever format.

So basically wrap over the actual stream with another forwarding stream to a FileStream.

**Comment by Therzok** [comment]
I haven't started working on it, but am planning to tomorrow.

**Comment by pGlase** [comment]
Okay, then I'll leave it to you

**Comment by Therzok** [comment]
*in progress*
