### ISSUE TITLE
Colors for the Local Player does not work since the refactor

### ISSUE THREAD

**Issue by hubastard** [hubastard/nebula#25]
Since the "host" refactor, the local player colors does not seems to be applied anymore. I looked at it quickly, the method that sets the colors is called and it looks like it is modifying the material but it must be reverted after is game loaded because there is no color change for the local client. Remote clients looks to be fine.

**Comment by hubastard** [comment]
@Flapperkewiet Would you like to look at it ?

**Comment by Flapperkewiet** [comment]
Ill look into it

**Comment by Flapperkewiet** [comment]
Ive been looking into it for hours now and can't seem to find anything usefull. The color is never changed by the game, its stored in the prefab.

Is there an update function I can hook into without writing a new patcher?

**Comment by hubastard** [comment]
Maybe the MainPlayer model reinstantiated on game load ? I'll take a look tonight after my day job, if you haven't found anyting since then

**Comment by Flapperkewiet** [comment]
I think i might have found the issue.

The player indeed changes. When we invoke `DSPGame.StartGameSkipPrologue(gameDesc);` in `UIMainMenu_Pacth::OnHostGameButtonClick` it internally creates an instance of `GameLoader` which in turn has a FixedUpdate function looking like this:

`
void FixedUpdate()
{
    if(frame == 1)
    {
        Some code
    }
    if(frame == 2)
    {
        Do some other things
    }
    if(frame == 3)
    {
        do some more work
    }
    frame++
}

So a new player is created inside one of those if statements and changes. So now i'm going to look if we can delay the PlayerColorChange packet. Maybe add a callback when the game finishes loading?



`

**Comment by hubastard** [comment]
If you can add a `OnGameLoadCompleted` callback that would be awesome, we also need to do this to fix #27

**Comment by hubastard** [comment]
The main issue that I found was that the game loader is also used to load the main menu since the main menu is also a game that is simulated under the hood. We would need to find a way to know that the game being loaded is the real multiplayer game not the main menu. One way that I can think of is to check if the MultiplayerClientSession exist. Since it's only created once you click the Join button

**Comment by Flapperkewiet** [comment]
Where should i put the callback? In the patch seems kinda akward

**Comment by hubastard** [comment]
You could probably add the handler inside the Simulated world class

**Comment by Flapperkewiet** [comment]
Is a multiplayerClientSession also created if you are the host?

**Comment by hubastard** [comment]
No the host will have a `MultiplayerHostSession`

**Comment by hubastard** [comment]
If you need to know if you are the host you can check `LocalPlayer.IsMasterClient`

**Comment by Flapperkewiet** [comment]
Yes, so i need to check if there is either a `MultiplayerHostSeesion` or a `MultiplayerClientSession`

**Comment by hubastard** [comment]
Also, if it helps I noticed that the gameTick is set to 0 while the game is loading and when the loading is done, the gameTick starts either at 1 for a new game our the previous gameTick that was saved in the save game.
