### ISSUE TITLE
Always restarts Tutorial.

### ISSUE THREAD

**Issue by TheRealMarine** [hubastard/nebula#253]
Is there anyway that you could disable the tutorial voice/UI. Everytime i restart the game it restarts the Tutorial. "Oh you built a furnace!" *kinda endgame already*
There will be a option to disable it from the devs in the future probably too but nothing until now atleast.

**Comment by hubastard** [comment]
We could add a checkbox in the setting to disable this after the setting PR is merged.
https://github.com/hubastard/nebula/pull/254
