### ISSUE TITLE
Auto Updater

### ISSUE THREAD

**Issue by TheRealMarine** [hubastard/nebula#268]
Not important but still a cool feature. Everytime you start DSP it checks for Updates on Github and downloads them. We could consider such feature in the future.

**Comment by Therzok** [comment]
Checking a new version exists is pretty easy. Downloading it automatically is a bit more complicated, since you need to run something after the game exits (file handles in use).

**Comment by TheRealMarine** [comment]
That's what i thought. We could also make an Exe which starts with DSP and checks in background if there is an Update. If there is, then close DSP and install the update and start DSP again.

**Comment by Therzok** [comment]
So basically a mod manager

**Comment by TheRealMarine** [comment]
Yea that definition hits good

**Comment by Lomeront** [comment]
A suggestion would be using Thunderstore Mod Manager.
https://dsp.thunderstore.io/

for what is in the current zip file it's missing the following files.
-  icon.png
-  README.md
-  manifest.json

https://github.com/thunderstore-io/Thunderstore#mod-package-format

**Comment by hubastard** [comment]
Yeah we plan to add the mod on Thunderstore soon. We are waiting for the next game update to make sure that the mod still works properly and we will add it to Thunerstore if everything is fine.

**Comment by hubastard** [comment]
Thunderstore release is now available
