### ISSUE TITLE
UpdateSlotData Array index is out of range.

### ISSUE THREAD

**Issue by Jon-Myrstad** [hubastard/nebula#273]
Same issue as was fixed for UIStationWindow and UIStationStorage fixed in #269.

![unknown](https://user-images.githubusercontent.com/7058316/116830813-40833f80-abac-11eb-90d7-1e82ef8f1035.png)

**Comment by sp00ktober** [comment]
I tried to reproduce this for 20 minutes now but i just cant :/
what did you do to trigger it @Jon-Myrstad ?
