### ISSUE TITLE
NebulaHost.PacketProcessors.Logisticts.ILSRequestShipsDockProcessor IndexOutOfRangeException

### ISSUE THREAD

**Issue by Jon-Myrstad** [hubastard/nebula#275]
- Host built a new ILS in a different star system (not sure if relevant)
- Client was in different star system and configured an ILS with ships and supplies for the newly built ILS.

![image](https://user-images.githubusercontent.com/7058316/116831990-0bc6b680-abb3-11eb-8a6c-3955d4a2e9ca.png)

**Comment by sp00ktober** [comment]
@Jon-Myrstad did yu face this with https://github.com/hubastard/nebula/pull/263 merged?

**Comment by sp00ktober** [comment]
Im kinda sure this is fixed already.
