### ISSUE TITLE
When host builds and ILS on a planet the client does not have loaded, the client never get to know about it

### ISSUE THREAD

**Issue by Jon-Myrstad** [hubastard/nebula#283]
- Completely empty game
- Research all the things 
- Fly host to another star
- Build ILS on another star with host (gId 1). From what I can see, the host never notifies the client about this, because the client doesn't request anything, because it doesn't know about it being built.
- Build ILS on starter planet with client (gId 2), but client does not know about gId 1 yet, so for the client, this is gId 1.

Now, the client will request data about gId 1 from the host when opening UIStationWindow, so the client actually sees gId 1 that is on another star, not it's local ILS (gId 2), and setting order doesn't work correctly from here an onwards. 

The host is basically not being "bossy" enough on most of this, causing issues.

**Comment by sp00ktober** [comment]
This is probbaly same as #245
