### ISSUE TITLE
Multiplayer Options Float Sliders Don't Have Proper Stepsize

### ISSUE THREAD

**Issue by PhantomGamers** [hubastard/nebula#285]
When adding a slider to a float config option, the logic of the step size should be:
`(!wholeNumbers) ? ((maxValue - minValue) * 0.1f) : 1f`

However, it's set to 1f regardless of what `wholeNumbers` is set to in the UIOptionWindow_Patch class.

I thought this might be because of how the slider is created before the patch assigns the values, so it wasn't considering that for the step size, but it looks like the values I'm assigning are the default values in the actual Slider class so it should have a step size of 0.1f.

**Comment by hubastard** [comment]
I'm looking at it right now
