### ISSUE TITLE
All players get refunded conveyor belts

### ISSUE THREAD

**Issue by Shad0wlife** [hubastard/nebula#290]
When connecting two belts with a belt of another tier, the endpoints of these belts get replaced with the newly built tier type, and the replaced lower tier belts get refunded. This specific refund is done for all players. Refunds by regular upgrading with the upgrade tool are not affected and seem to work as intended.

Gif of how to reproduce (the refund you can see happening is given to all players):
![BeltBug](https://user-images.githubusercontent.com/15235997/117336403-753d1280-ae9c-11eb-9c22-0d5b6b3839e0.gif)

**Comment by pGlase** [comment]
Was tested on newest build from server artifact of #288

**Comment by PhantomGamers** [comment]
Fixed by f0cc341
