### ISSUE TITLE
[Feature] Can change port of Host

### ISSUE THREAD

**Issue by RainSunMe** [hubastard/nebula#292]
My friends and I are not on the LAN. So I used my public network server to build the Frp service.
But now the port can only be 8469, can only be used by a pair of players at the same time.
If we can modify the port, one server can let more friends play at the same time.
Thanks.

**Comment by RainSunMe** [comment]
A port can be used by a host and a client
What I mean is that by changing the port, multiple pairs of users can use the same public network server
Looking forward to the latest build. (*^▽^*)

**Comment by RainSunMe** [comment]
A port can be used by a host and a client
What I mean is that by changing the port, multiple pairs of users can use the same public network server
Looking forward to the latest build. (*^▽^*)

**Comment by PhantomGamers** [comment]
One port is set by the host, and many clients can connect to the server on the same port, as long as the port is open on the host's end.

**Comment by RainSunMe** [comment]
Really ? !  I didn't know this until now, it's so cool !
