### ISSUE TITLE
conveyor belt stuck in bulid mode

### ISSUE THREAD

**Issue by ssexybkackman** [hubastard/nebula#293]
a hand full of conveyor belts are stuck in the blue build mode and when i go to remove it, it does not delete, aslo all my little builders keep on trying to build it but does not build so i cant build anything anymore.

**Comment by hubastard** [comment]
Try to reconnect. Usually this solves most of the issues that can occur right now.

**Comment by zhuzhe1983** [comment]
Reconnect won't fix this problem.  thoese blet with yellow/green/blue dots will never be built and can't be deleted. i think it become bad data in the game. even after the server rehost the game, those blet are still there, remain the bulid mode and never be done. Drones keep flying to those build mode blet and make robot lose power.

There is another bug with the green build blueprint can be fixed  by reconnect the game...

**Comment by Heurazio** [comment]
Same error here. It's really annoying because there is nothing that really can be done with it. Anyways, the host can interact with the remove tool but instead of deleting the dot host just gets the items that er in the incorrect "blueprint" while a client can not interact at all.

**Comment by PhantomGamers** [comment]
This issue should already be fixed on the latest builds from github actions

**Comment by Heurazio** [comment]
It can also be fixed when loading a save file in single-player mode. 
@PhantomGamers Is it for 0.6X ? Where can I find it ?

**Comment by PhantomGamers** [comment]
https://github.com/hubastard/nebula/actions/runs/851960762

**Comment by Heurazio** [comment]
I can just replace the content of the `Dyson Sphere Program\BepInEx\plugins` Folder with the content of the release build I guess? Thanks for your help.

**Comment by PhantomGamers** [comment]
You want to replace the old Nebula files with the old ones, not sure how you had it installed to begin with.

The NebulaClient.dll and all of the other files should replace your current ones.
