### ISSUE TITLE
[0.7.x] StationComponent.InternalTickLocal Array out of bounds

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#295]
`[Error  : Unity Log] IndexOutOfRangeException: Array index is out of range.
Stack trace:
StationComponent.InternalTickLocal (int,single,single,single,int,StationComponent[]) <0x00768>
PlanetTransport.GameTick (long,bool) <0x004fb>
(wrapper dynamic-method) PlanetFactory.DMD<PlanetFactory..GameTick> (PlanetFactory,long) <0x00159>
(wrapper dynamic-method) GameData.DMD<GameData..GameTick> (GameData,long) <0x002a2>
(wrapper dynamic-method) GameMain.DMD<GameMain..FixedUpdate> (GameMain) <0x0027a>`

**Comment by sp00ktober** [comment]
This also happens on the new game version and is most likely due to desync of drones amount in stations (client can overflow it)

**Comment by hubastard** [comment]
@sp00ktober Is this fixed in mod version 0.2.0 ?

**Comment by sp00ktober** [comment]
No not yet, but it should only be possible to trigger it by breaking out of the station ui sync (there is also an issue for that but im on the phone right now)
