### ISSUE TITLE
An error about the interface display after use the ILS/PLS 

### ISSUE THREAD

**Issue by zypriest** [hubastard/nebula#298]
After the client interacts with the ILS/PLS enough times. If you exit and connect again，then the Interface display error.
![image](https://user-images.githubusercontent.com/73626837/118424810-7bcc5500-b6fa-11eb-9feb-f40a5ca47cc4.png)
![image](https://user-images.githubusercontent.com/73626837/118424821-81c23600-b6fa-11eb-9866-26e9707a8ccc.png)

What's more, I find that the client can't add the Logistics transport aircraft for the PLS but can do it for LPS.

**Comment by zypriest** [comment]
When both the host and client exit game and restart, Everything is back to normal. But the situation above may happen repeadly.

**Comment by sp00ktober** [comment]
dublicate of #267 but nice screenshots :D

**Comment by sp00ktober** [comment]
Closed as it was not reported again for a long time.
