### ISSUE TITLE
Save the mod settings as json or other format

### ISSUE THREAD

**Issue by hubastard** [hubastard/nebula#300]
We should save the multiplayer mod settings as json instead of binary, that will make sure that we are able to easily add or remove fields in the save without causing some deserialization errors.

**Comment by PhantomGamers** [comment]
Maybe it would be preferably to simply use the [BepInEx ConfigFile class](https://bepinex.github.io/bepinex_docs/master/articles/dev_guide/plugin_tutorial/3_configuration.html) for this instead?

**Comment by PhantomGamers** [comment]
It might be good to just use https://github.com/Fuhduki/FuhdukiDSPMod/tree/main/BepInExConfig as this would make the process of switching to the BepInEx system pretty seamless with our current system I think.

**Comment by hubastard** [comment]
Working on it now
