### ISSUE TITLE
Players get wrong inventory

### ISSUE THREAD

**Issue by PhantomGamers** [hubastard/nebula#302]
Sometimes on connect, players will get the wrong inventory.

If I'm not mistaken, which I might be, it seems to just apply inventories based on the order in which players connect?

Instead of using this, we should be assigning the player data to a unique identifier of a client. Using the Steam ID for this would probably be ideal. I remember seeing a discussion of this somewhere else but I can't seem to find it, and I think this was up for discussion because the game might be on non-steam platforms as well?

**Comment by Mushroom** [comment]
This should absolutely not be the case - clients generate a keypair and present the public key as their identifier, which the server uses to look up their details for things like the inventory etc.

Do you have steps to reproduce this? What does your environment look like, are you playing over LAN, WAN?

**Comment by PhantomGamers** [comment]
Ah OK I didn't see that.

The best way to trigger the different player data seems to be to have a client terminate the process (alt+f4 works) so that it can't gracefully disconnect, and then have the client reconnect, and they will be assigned a completely different playerData. Though sometimes it seems to assign incorrect playerData on initial connection as well.

I am playing over WAN and this happens with the latest codebase.

**Comment by Therzok** [comment]
Looking over the code, there are sparse locks mutating player sync information, which could end up with partial state initialization that is not reset on connection failure?

Or, maybe the client sends some inventory update on login and messes with the host data?

Sounds like a race condition, overall

**Comment by Therzok** [comment]
Hmmm, so even if client cert hash is used to look up player data, the associated IDs for a player can still be rehashed.

See GetNextAvailablePlayerId. This basically means that a player disconnect will leave an ID up for grabs, so if the data in the save file only encodes player id, it is possible to create mismatched data.

I haven't checked yet but I assume the saved data is loaded with an indexer instead of add, so the possibility of having 2 colliding IDs still exists.

**Comment by Therzok** [comment]
https://github.com/hubastard/nebula/blob/2ff78304c50066e36bdfd3defdfe6506d634bbb1/NebulaHost/Player.cs#L30

It is saved by hash: https://github.com/hubastard/nebula/blob/94ac4c7e7e8d4e60736383e55bc60828f9933968/NebulaHost/SaveManager.cs#L27

**Comment by Therzok** [comment]
Maybe it's worth adding some warning logging in case the public key hashes collide?

**Comment by Therzok** [comment]
There is this patch that seems to fix behaviour around autosave files: https://github.com/hubastard/nebula/commit/792ffa0ef9b821db6254bb7c17bf26c6b3e342ae

**Comment by PhantomGamers** [comment]
I think I figured out what the issue is, it's that sometimes when the game is started it uses the "Dyson Sphere Program" folder within the DSP game folder rather than the documents folder, so there can be two separate player.key files generated and loaded depending on which folder the game decides to use. This is the same issue that causes players saves to "go missing." Perhaps we should pick a more reliable path?

**Comment by PhantomGamers** [comment]
This is worked around by https://github.com/PhantomGamers/nebula/commit/5bc169f8cce36cb72aa56fae50dd65768b84145a
