### ISSUE TITLE
EM Rail Ejectors not shooting for client at load

### ISSUE THREAD

**Issue by Smethan** [hubastard/nebula#303]
EM Rail Ejectors don't appear to shoot on the client's side until they load in the planet they are launching from, which leads to a desync in the dyson swarm sail count. It doesn't appear to affect the generation of power by Ray Receivers, but still something that I believe _could_ cause issues with the actual sphere construction

**Comment by sp00ktober** [comment]
This could actually be tricky. Im not sure at how the current code handles it, but i guess it relies upon the `PlanetFactory` being loaded. We only do that when approaching a planet which causes this problem.

Maybe we should only sync the solar panels beginning from the time where they are shoot to all players in that system so it does not require the `PlanetFactory` anymore.
