### ISSUE TITLE
[0.7.x] Build placement syncing

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#309]
So here is the first ingame issue, placing buildings. No error thrown.

When client places a building he sends out a drone, but the building is never build upon arrival.
Host does not see the prebuild

When host builds something else near that place he will build the building the client placed, but only client will see it.

I made a video but blame vodafone for the bad upload speed that they give me today... (i cant upload atm)

**Comment by NoGTNoHappy** [comment]
This issue is caused by [Quickfix](https://github.com/hubastard/nebula/pull/307/files#diff-9544224eda2352a0aeafab2de49083e85ed097e13caa21f9cfa5bc5744b2690cL12-L72) for successful compilation. Prebuild-related features need to be fix up.

**Comment by sp00ktober** [comment]
![grafik](https://user-images.githubusercontent.com/79335616/121027880-9b114c00-c7a7-11eb-984e-162c7c353d5f.png)

https://github.com/hubastard/nebula/pull/307/commits/831cda6471b42166a9f1a7186b5a8f0b09412ddf fixed it for starting planet but client still cant build on other planets

**Comment by PhantomGamers** [comment]
That is caused by the planetid on the client being mismatched from the planetid on the host. Further investigating is needed.

**Comment by sp00ktober** [comment]
fixed in #314
