### ISSUE TITLE
[0.7.x] Client hangs when leaving starting star system

### ISSUE THREAD

**Issue by PhantomGamers** [hubastard/nebula#312]
No error is printed before the hang so more research is needed

**Comment by PhantomGamers** [comment]
The cause is the same as when the client hangs on joining a server where they are placed in a different star system from the host.

An NRE is generated in WorkerThreadExecutor.InserterPartExecute() at line 295 because factorySystem is NULL.

**Comment by sp00ktober** [comment]
Wow this was an easy oneliner fix, im pushing it to the pr and close thise one after.
