### ISSUE TITLE
[0.7.x] NRE when placing building over vegetation

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#313]
`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
NebulaWorld.SimulatedWorld.OnVegetationMined (NebulaModel.Packets.Planet.VegeMinedPacket packet) (at <ba80609d38f042faa61622489474438f>:0)
NebulaHost.PacketProcessors.Planet.VegeMinedProcessor.ProcessPacket (NebulaModel.Packets.Planet.VegeMinedPacket packet, NebulaModel.Networking.NebulaConnection conn) (at <de9bb42c3ef54c3c8e1bb710e01eba81>:0)
NebulaModel.Networking.Serialization.NetPacketProcessor+<>c__DisplayClass34_02[T,TUserData].<SubscribeReusable>b__0 (NebulaModel.Networking.Serialization.NetDataReader reader, System.Object userData) (at <0b96cf96f0ac4d06a62f61921d3c04d1>:0)
NebulaModel.Networking.Serialization.NetPacketProcessor.ReadPacket (NebulaModel.Networking.Serialization.NetDataReader reader, System.Object userData) (at <0b96cf96f0ac4d06a62f61921d3c04d1>:0)
NebulaModel.Networking.Serialization.NetPacketProcessor.ProcessPacketQueue () (at <0b96cf96f0ac4d06a62f61921d3c04d1>:0)
NebulaHost.MultiplayerHostSession.Update () (at <de9bb42c3ef54c3c8e1bb710e01eba81>:0)`

Error pops up on both client and server when constructing a building does remove vegetation.

**Comment by PhantomGamers** [comment]
This is on line 292 of NebulaWorld/SimulatedWorld.cs

**Comment by sp00ktober** [comment]
fixed
