### ISSUE TITLE
[0.7.x] clients freeze when joining old game saves

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#315]
When hosting saves created before 0.7.x updates (which does work) joining clients freeze on the join loading screen.

No error, host loading popup does vanish. Not sure whats causing this.

**Comment by sp00ktober** [comment]
after dd2e6b7 clients can now join but get an error spam:
![grafik](https://user-images.githubusercontent.com/79335616/121196940-2e628400-c871-11eb-9b86-8e731478f593.png)

**Comment by PhantomGamers** [comment]
This error is caused by StationComponent_Transpilers.cs:765

**Comment by sp00ktober** [comment]
fixed the reverse patch in 620a229 and old saves seem to load fine now (they did before this commit too, actual fix was dd2e6b7 )
