### ISSUE TITLE
[0.7.x] Index Out of bounds CargoPath.Update()

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#326]
![grafik](https://user-images.githubusercontent.com/79335616/121953915-6df00b00-cd5e-11eb-84b6-78bec901ee49.png)
![grafik](https://user-images.githubusercontent.com/79335616/121953963-7f391780-cd5e-11eb-80d1-c69e0a6dc697.png)

No reliable way to reproduce the issue yet

**Comment by PhantomGamers** [comment]
I'm thinking this is likely related either to the AfterPrebuild() stuff that I never implemented here:
https://github.com/Mushroom/nebula/blob/may2021-patch-fix/NebulaClient/PacketProcessors/Factory/Entity/CreatePrebuildsRequestProcessor.cs#L100

Or the CheckAndFixConnections() code here:
https://github.com/Mushroom/nebula/blob/may2021-patch-fix/NebulaHost/PacketProcessors/Factory/Entity/CreatePrebuildsRequestProcessor.cs#L156

**Comment by hubastard** [comment]
@PhantomGamers  Is this fixed in mod version 0.2.0 ?

**Comment by PhantomGamers** [comment]
> @PhantomGamers Is this fixed in mod version 0.2.0 ?

Yes I believe so
