### ISSUE TITLE
[0.7.x] NRE MechaDroneLogic

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#329]
![grafik](https://user-images.githubusercontent.com/79335616/122682611-c6aa2280-d1fa-11eb-8b89-e8b5f14dbe35.png)
When client has drones flying/building stuff while leaving planet this can happen.

**Comment by PhantomGamers** [comment]
possibly fixed by https://github.com/PhantomGamers/nebula/commit/ca267414f7c431ea01d12145c70ccbd2fd5a222a

**Comment by PhantomGamers** [comment]
maybe fixed by #493
