### ISSUE TITLE
Players clumb together once localPlanet gets null

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#33]
![movementSpace](https://user-images.githubusercontent.com/79335616/110324145-e20b6c00-8015-11eb-9016-1d033467dd26.jpg)
rotation is still applied but the stick together until localPlanet of atleast one of them gets non-null again.

**Comment by hubastard** [comment]
Alright, so I've been doing some digging and it's exactly what I thought. So to avoid floating point precision issues, what they did is that while the player is on a local planet, the planet is your world origin and they move the player physically around the planet. But then as soon as you leave the planet and you are moving in space, they are doing a clever trick of instead snapping the player to the position 0,0,0 in the world, the player never moves, its the world / planets that move towards the player.

That way the player will never experience floating point imprecision when the floating point number becomes to big.

**Comment by sp00ktober** [comment]
We can just compare the localPlanet.id too determine who needs to be visible and who needs to be hidden.

**Comment by Flapperkewiet** [comment]
But what if 2 players are in space? Wouldnt they both be at the origin?

**Comment by sp00ktober** [comment]
I guess thats whats happening, see the image at the top

**Comment by Flapperkewiet** [comment]
Yupp, so either we make it so players cant see eachother in space, or we need to calculate an offset to render remote players

**Comment by sp00ktober** [comment]
I think players should be able to see each other in space, else it would look really weird if you fly together and the other disappears suddenly.

**Comment by hubastard** [comment]
I'm currently working on this
