### ISSUE TITLE
[0.7.x] error when entering new solar system

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#331]
![grafik](https://user-images.githubusercontent.com/79335616/122477250-b8c08b80-cfc7-11eb-9fe7-0f0753c9a2fa.png)
On client when warping into another system
![grafik](https://user-images.githubusercontent.com/79335616/122477289-c249f380-cfc7-11eb-8992-c2710b432e55.png)
on host when that happens (maybe not related)

**Comment by PhantomGamers** [comment]
this is related to #327 and https://github.com/hubastard/nebula/pull/307/commits/4e6a5341c845cbb81c984e818aa2409af7159e5b

nearestFactory doesn't NRE anymore but things that depend on it do. Makes sense, but I'm not sure why I wasn't able to trigger this prior to the update.

**Comment by PhantomGamers** [comment]
worked around by https://github.com/PhantomGamers/nebula/commit/2da47131791b1693a4a530fa9e205eb6388cb7fc

**Comment by sp00ktober** [comment]
closed for now
