### ISSUE TITLE
[0.7.x] NRE ArriveStar_Prefix

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#334]
![grafik](https://user-images.githubusercontent.com/79335616/122808765-93849380-d2cd-11eb-97a0-008bde4bba48.png)
was fixed by reverting to older save

**Comment by PhantomGamers** [comment]
Most likely the same as #338 and also fixed by https://github.com/PhantomGamers/nebula/commit/0b248bd46b522d6990b4f216c13e1a0c336740ba

**Comment by PhantomGamers** [comment]
Pretty sure this can be closed
