### ISSUE TITLE
Mining vegetation and veins can cause an IndexOutOfRangeException

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#34]
This only happened so far when i played with a friend over the network (so kinda the real world scenario).
I will work on a fix asap.
![VeinSyncError](https://user-images.githubusercontent.com/79335616/110324371-25fe7100-8016-11eb-908d-f5d959c30114.jpg)

**Comment by sp00ktober** [comment]
cannot reproduce this anymore, so putting it back for now.

**Comment by hubastard** [comment]
Will close it for now, we can reopen if we find better repro steps
