### ISSUE TITLE
[0.7.x] Settings don't sync when pasting from copied building preview

### ISSUE THREAD

**Issue by PhantomGamers** [hubastard/nebula#342]
Copying and pasting with , and . sync, but doing the same by placing build previews with desired settings does not.

**Comment by PhantomGamers** [comment]
fixed by https://github.com/PhantomGamers/nebula/commit/72129041bdbb92dab573404819d3df1cbba9ebd0

**Comment by HearthCore** [comment]
> Copying and pasting with , and . sync, but doing the same by placing build previews with desired settings does not.

Additionally, Sorters are copied and placed, regardless of legal attachment orientation. Sorters may hang in open air.
