### ISSUE TITLE
[0.7.x] Client can become unable to take items from ILS under certain conditions

### ISSUE THREAD

**Issue by PhantomGamers** [hubastard/nebula#343]
Steps to reproduce as client:

1. Open an ILS's storage.
2. Quickly open different ILS storage windows without closing them first
3. Client becomes unable to right click to withdraw items from ILS until they close the ILS window

**Comment by PhantomGamers** [comment]
Related: https://github.com/hubastard/nebula/issues/343

**Comment by sp00ktober** [comment]
Probably same as #234
