### ISSUE TITLE
Sync Player Effects

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#35]
sync the important visual and sound effects.

- [ ] #33 blocks part of tests that need to be done to complete this

Current status:
- sparkles are synced
- thrusters are mostly synced
- thruster audio effect synced on planet and space
- mining electric audio effect synced
- footsteps visuals and audio synced
- vegetation collide sound effect synced
- landing sound effect synced
- warp visuals/audio (needs some optimization)

Whats missing:
- clean up code

**Comment by hubastard** [comment]
#33 is now fixed and merged into master. You should be able to finish this now.
