### ISSUE TITLE
Sync buildings build during gameplay to other players

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#36]
If one player places a building other players need to see the same and need to be able to interact with it as if they had build it by them self.

Current status:
- buildings get placed for each player on the same planet
- terrain is flattened for each player on the same planet if needed
- miners connect to the same veins.
- power generators register as generators to the power system, consumer register as consumer.

[video preview](https://www.youtube.com/watch?v=Uf46E3Zx5-4)

**Comment by hubastard** [comment]
Further bugs / improvement will be opened in new issues.
