### ISSUE TITLE
Manually harvested resources are not sync

### ISSUE THREAD

**Issue by graille** [hubastard/nebula#361]
This is a synchronisation issue

Let's imagine a coal node of 1000 units, if the client (resp the host), manually harvest 100 units of coal, the client (resp the host) will see a node a 900 units, but the other player will still see a full node with 1000 units of coal.

If the client leave the game and reconnect to the game, the amount of resources in the node is resynced with the current amount of the host, even if the client mined some resources (possibily an infinite resources generation bug here).

Don't know what happen if one player harvest all the node manually.
This doesn't happen when miners are used.

**Comment by sp00ktober** [comment]
oof thanks for the hint. it was working again but seems like it broke on the way to the release, will make a fix for it.
