### ISSUE TITLE
Only  Multiplayer mode have error reports

### ISSUE THREAD

**Issue by Zhouttt** [hubastard/nebula#372]
After replacing the archive, an unknown error resulted in 200000 error reports
(https://user-images.githubusercontent.com/56289021/125572375-0360f10f-622f-472f-a594-94c2f175e44a.png)

**Comment by PhantomGamers** [comment]
this will be fixed by #373

**Comment by Zhouttt** [comment]
Thank you. I can continue to play with my friends
