### ISSUE TITLE
Interplanetary transport system cause error

### ISSUE THREAD

**Issue by graille** [hubastard/nebula#375]
When I started to use interplanetary station and add some ship in it. This error occured.
Restart the game do not fix the issue.

![error](https://user-images.githubusercontent.com/7689997/125636163-caa0b178-42a2-426c-a4cc-d02094fce08e.png)

**Comment by sp00ktober** [comment]
*maybe* this is caused by adding more drones/vessels than the max amount to the station, this can be caused by #234

**Comment by sp00ktober** [comment]
Closed because it was not reported again for a long time.
