### ISSUE TITLE
源代码无法编译

### ISSUE THREAD

**Issue by HereFack** [hubastard/nebula#404]
你的源代码无论是修改过还是没有修改过,他都无法编译! C#告诉我,你的源代码有很多地方有错误!我希望你能将正确的源代码发布出来!
Your source code will not compile with or without modification! C# tells me that your source code has a lot of errors!I hope you can release the correct source code!

**Comment by PhantomGamers** [comment]
Follow the instructions here to compile: https://github.com/hubastard/nebula/wiki/Setting-up-a-development-environment
