### ISSUE TITLE
Add Discord Rich Presence support

### ISSUE THREAD

**Issue by PhantomGamers** [hubastard/nebula#406]
https://support.discord.com/hc/en-us/articles/115001557452-Game-Invites-and-Detailed-Status-Rich-Presence-

We should support:
- Displaying that the user is in a multiplayer game along with the star and planet they are in.
- Display how many other players are in the same game as the user
- Allow inviting people through discord, and of course allowing people to actually accept invites.

Integration information: https://discord.com/developers/docs/game-sdk/activities

**Comment by mmjr-x** [comment]
I have started with this :) seems like a fun challenge!

**Comment by mmjr-x** [comment]
@PhantomGamers Since you did this, this issue can probably be closed :)
