### ISSUE TITLE
When a player joins, the host may not respond

### ISSUE THREAD

**Issue by shoucandanghehe** [hubastard/nebula#407]
Our file size is now 178mb
When the player joins the game, the host may not respond and crash.

**Comment by NoGTNoHappy** [comment]
Maybe the same as #401

**Comment by shoucandanghehe** [comment]
maybe?
But when this error occurs in our game, the host will first display "player joining the game" but the keyboard can continue to operate the game, and it will crash after a while.
Players who try to enter the game will first enter the loading interface, and then return to the join game interface, and the loading prompt box will not disappear.
And our host has an upload speed of 100mbps+

**Comment by NoGTNoHappy** [comment]
Did you ever encounter this problem with much less savefile size, such as 20mb?
Did DSP give any red error message on the top right side either host or client?

**Comment by sp00ktober** [comment]
Closed in favor of #401
