### ISSUE TITLE
Belt gaps when other players mass deleting

### ISSUE THREAD

**Issue by scrmjt** [hubastard/nebula#411]
When host building belts and client is mass deleting items, there are gaps that appear in the placed belt. See example picture.

![image](https://user-images.githubusercontent.com/10900894/127748454-2bdc3a69-a006-4a45-8d89-a2ca70be9c9e.png)

Early Acces 0.8.19.7757
Nebula v0.3.1-241b5b3

**Comment by starfi5h** [comment]
Can't reproduce in the current version.
