### ISSUE TITLE
[docs] Please update Install docs with more details

### ISSUE THREAD

**Issue by Darkentik** [hubastard/nebula#424]
Hey i tried to install BepInEx with your instructions but it didn´t work.
PLease be so kind and update your install instructions.
Thanks a lot.

**Comment by PhantomGamers** [comment]
The guide gives you the full instructions on how to manually install nebula. I'm not sure what more can be added?

**Comment by Darkentik** [comment]
But the instructions did not work.
I have now got a link for steamcommunity from the discord server.
Here a mod manager is used.
It is very good.
https://steamcommunity.com/sharedfiles/filedetails/?id=2551456741

**Comment by PhantomGamers** [comment]
We should include instructions that point people to the mod manager, but the instructions that are given do work.

If you post a picture of your game install folder I can see what is missing

**Comment by hubastard** [comment]
Read me have been updated
