### ISSUE TITLE
Unlimited Resources and instant crafting/research

### ISSUE THREAD

**Issue by Desaren** [hubastard/nebula#429]
When mod is installed, the recipes cost no resources and instant craft as well as research being instantaneous.  This happens is multiplayer session and single player.

![image](https://user-images.githubusercontent.com/43919932/131339768-bcb2a39b-acce-44bc-bdfd-9489d3c9c59c.png)

**Comment by Desaren** [comment]
Not sure why it didn't include my red circle from MS paint, but the picture is showing that I can craft >999 of the item which is obviously not true.

**Comment by Mushroom** [comment]
You have installed the debug rather than release version

**Comment by Desaren** [comment]
I feel dumb, thank you
