### ISSUE TITLE
Planet Terrain not synced on load

### ISSUE THREAD

**Issue by PhantomGamers** [hubastard/nebula#437]
Planet terrains are only synced when the client loads a star initially, and then is not resynced when the client first lands on a planet.
![image](https://user-images.githubusercontent.com/844685/132925595-f1540928-91c1-48b8-9011-80913b48a9f4.png)

**Comment by sp00ktober** [comment]
Could it be eough to call this for clients? https://github.com/hubastard/nebula/blob/b636bdf26649a806ea67f33ecaaee875b2eac56f/NebulaPatcher/Patches/Dynamic/PlanetModelingManager_Patch.cs#L94

**Comment by PhantomGamers** [comment]
I tried that but it tended to result in the planet disappearing for me and then a bunch of errors related to the player position (so maybe the planet didn't disappear and the player just got yeeted somewhere else). It was very strange, but I didn't look into it much further
