### ISSUE TITLE
Hope to adapt to the new version 0.8.21.8562

### ISSUE THREAD

**Issue by Xunflash** [hubastard/nebula#440]
There is no Mutiplayer button after opening the game.

**Comment by joshsanderlin** [comment]
Same here, tried using manual installation and with r2 but no Multiplayer button in either case.

**Comment by TheDurtch** [comment]
Multiplayer not loading
attaching logs

[LogOutput.log](https://github.com/hubastard/nebula/files/7181694/LogOutput.log)

**Comment by dadajuan718** [comment]
The multiplayer button is missing after the update,hope the almighty author can update the mod.

**Comment by juehv** [comment]
same here ! I'm pissed that I installed the update :D

**Comment by hubastard** [comment]
Yes we are aware and working on fixing the mod, they did quite a lot of changes to the player mecha scripts that we need to update our mod to be compatible with. This could take a couple of days to fix properly.

**Comment by aizhengtai** [comment]
MOD has expired

**Comment by hubastard** [comment]
A new version is available! Thanks to @PhantomGamers  and @starfi5h
You can get the new version on thunderstore: https://dsp.thunderstore.io/package/nebula/NebulaMultiplayerMod/
Or install it manually from Github: https://github.com/hubastard/nebula/releases/tag/v0.6.0

**Comment by Xunflash** [comment]
> A new version is available! Thanks to @PhantomGamers and @starfi5h You can get the new version on thunderstore: https://dsp.thunderstore.io/package/nebula/NebulaMultiplayerMod/ Or install it manually from Github: https://github.com/hubastard/nebula/releases/tag/v0.6.0

![image](https://user-images.githubusercontent.com/71567536/135452889-46058cc4-3d1a-49a4-922e-1a6134943cd9.png)
new version again :(
