### ISSUE TITLE
Nebula 0.6.0 breaks when loading player data from previous versions

### ISSUE THREAD

**Issue by PhantomGamers** [hubastard/nebula#445]
![image](https://user-images.githubusercontent.com/844685/133947704-446dd7ba-dab3-4756-9b8b-703d2cc969c4.png)

This is caused by the change of the MechaColor part of the data to be a Float4[] instead of a Float3, to support the color changing that has been implemented officially in the game.

We should introduce versioning in the player data so that we can handle issues like this gracefully in the future.

I'm not sure if we can fix it so that we can add versioning **and** support pre-0.6.0 versions now that 0.6.0 is out and "contaminates the pool."

Perhaps we can have two checks: 
1. Whether a data revision is specified initially
2. If the data revision isn't specified, try catch this 
https://github.com/hubastard/nebula/blob/2b11c30e9e488e2a3b8388b06c8e653c1d778988/NebulaModel/DataStructures/PlayerData.cs#L55 and if it errors we can probably assume that it is a pre-0.6.0 data and then try to process it as it was before 
https://github.com/hubastard/nebula/blob/4e82547038a6d776dbe9252dc3de6126dd41a145/NebulaModel/DataStructures/PlayerData.cs#L51

**Comment by TuRzOp** [comment]
@PhantomGamers Hi do you know a way we could fix this issues while waiting for an update?

**Comment by PhantomGamers** [comment]
> @PhantomGamers Hi do you know a way we could fix this issues while waiting for an update?

You can load the save in single player and save it again, or navigate to the saves folder and delete the .server file that accompanies your save. Either will do the same thing, which will result in you losing client inventory and position data.

**Comment by TuRzOp** [comment]
Great thanks for the help! We had to delete the .server file to get it to work. The error persisted after I went and saved in single player so fyi

**Comment by PhantomGamers** [comment]
> Great thanks for the help! We had to delete the .server file to get it to work. The error persisted after I went and saved in single player so fyi

You'd have to save it under a different name, I should have clarified.

**Comment by freezeAll** [comment]
nebula/NebulaModel/DataStructures/PlayerData.cs  
` public void Deserialize(INetDataReader reader){` 
`            Username = reader.GetString();`
`            PlayerId = reader.GetUShort();`
`            LocalPlanetId = reader.GetInt();`
`            MechaColors = new Float4[1];`
`            var MechaColor = reader.GetFloat3();`
`            MechaColors[0].x = MechaColor.x;`
`            MechaColors[0].y = MechaColor.y;`
`            MechaColors[0].z = MechaColor.z;`
`            LocalPlanetPosition = reader.GetFloat3();`
`            UPosition = reader.GetDouble3();`
`            Rotation = reader.GetFloat3();`
`            BodyRotation = reader.GetFloat3();`
`            Mecha = new MechaData();`
`            Mecha.Deserialize(reader);`
` }` 
I don't know why,but it work,and other player's inventory is exist:
①I compile it and enter the game.
②And then save the data and exit game.
③Revert mod to the newest version,done.
