### ISSUE TITLE
Player gets teleported to the sun

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#46]
When you host a game and join the game with the second game instance before the first one could fully load the game one of the players gets teleported to the sun.

Not sure if that only happens to me so it would be good if someone could confirm this, tested on the master branch.

**Comment by IceCrafter** [comment]
I tested it and it appears to be consistent. The player starting the session gets teleported to/into the Sun upon another player joining early. The second player was always unaffected, perfectly fine on the starting planet. Tested on localhost on two PC's, and joined one Instance with an Instance on another PC, and the result was always the same. Hope that helps!

**Comment by hubastard** [comment]
I tested this and it's cause by the `GameMain.pause()` while the host is loading.
