### ISSUE TITLE
LangVersion in the project

### ISSUE THREAD

**Issue by Therzok** [hubastard/nebula#47]
Currently, the project is using the default langversion (C# 3), but the langversion can be upgraded to at least C# 7.3 without any problems at least, and this includes the ability to use `ref locals`.

With `ref locals` you can avoid the penalty of struct copies and other stack copies, that could add up in the context of a multiplayer computation.

This should be as simple as adding `<LangVersion>7.3</LangVersion>` to the csproj files.

**Comment by Mushroom** [comment]
Sounds like a good starter contribution to get acquainted with the project :)

**Comment by Therzok** [comment]
Oh, definitely, I just need to prioritize a few things in my list and I'll get to it and probably improve a few more things in the csproj for maintainability.

**Comment by Therzok** [comment]
Already fixed.
