### ISSUE TITLE
Trying to upgrade a blueprint "ghost" results in an IndexOutOfRangeException

### ISSUE THREAD

**Issue by hashworks** [hubastard/nebula#475]
Trying to upgrade ("Upgrade Facilities (U)") a blueprint "ghost" results in an `IndexOutOfRangeException` in `NebulaPatcher.Patches.Dynamic.PlanetFactory_patch.UpgradeFinally_Prefix`.

![error](https://fb.hash.works/M2F2y/)

**Comment by PhantomGamers** [comment]
this will be fixed by #474
