### ISSUE TITLE
Weird planet moving when loading factory data from server

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#48]
https://user-images.githubusercontent.com/79335616/111137696-6498ac00-857f-11eb-91e1-411bc74dd67f.mp4

Afaik this is due to loading the `PlanetFactory` from the server. It does not happen for Player 1 (the hosting one) or if you disable this feature for the others.

The error that pops up in the corner is fixed by [this patch](https://github.com/sp00ktober/nebula/commit/e9d2f3c8302751564e9cda6ecbe425ed916344e8)

- It seems like the weird planet movement starts when `ArrivePlanet()` or `RequestLoadPlanetFactory()` (this is where we patch and the request gets triggered) gets called.
- It seems like planet comes back to normal after `LoadingPlanetFactoryMain()` finished atleast one of its steps (not sure if it comes back sometime after the last step or sometime inbetween).
- `ModelingPlanetMain()` is only called once when you load the game, so its unlikely that the cause is in there.
- `uPosition` of player and planet do not change significantly between the weird movement of the planet.
- `GameMain.mainPlayer.transform.position` does change from `0 0 0` before the request to some coordinates after the request, but does not change when the planet comes back to normal. I dont think its related to this either.

Tested on master branch.

**Comment by Mushroom** [comment]
This might be related to the gametick syncing we do - possibly stale data is loaded from P1, then when the gametick is updated after the factory is loaded in, the planet snaps back to where it should be.

**Comment by sp00ktober** [comment]
it is comming back to normal faster with #45

**Comment by sp00ktober** [comment]
fixed by [this commit](https://github.com/sp00ktober/nebula/commit/3d70c0b8c245c002fb9c256f838449f4ecb87219)

the way its done now "locks" the player at the edge between space and the max radius of the planet where `localPlanet` would be set until the factory is loaded. As this happens pretty fast (well atleast for the planet we have here) this is nearly not noticable.

It gets noticable tho when you arrive with full speed, so we may need to load the factory way before the game would normally do it to make this more smooth.

Should this smoothing be part of this issue or can we close here?

**Comment by hubastard** [comment]
Nice job, as of the smoothing fix I suggest to do it later when we will be in a polish phase. For now we can focus on having a working feature first.

**Comment by sp00ktober** [comment]
Tested this in a real world case with a friend. Seems like we receive the factory too slow. While sending and loading the factory the game freezes for both of us, and for him (comming back from space to the planet) the planet looked frozen but its name was still moving "normally". Once the factory was loaded the planet moved to its name position and he could land there normally.

I guess we need to fix the freezing for this to work properly so that the planet keeps moving while receiving and loading the factory.
I will investigate further once i get some time.
