### ISSUE TITLE
Stacking Buildings Bug

### ISSUE THREAD

**Issue by Nocturnal42** [hubastard/nebula#494]
I have noticed when stacking storage, particularly if I place multiple without allowing the one underneath the finish, that the storage on top becomes bugged, and no more storages can be placed on top. It also cannot be deleted giving a "Target covered by other object", though the storage underneath it can be deleted, leaving the bugged storage floating in mid air. It is also not connected to the storage underneath and will not pass or receive items.

**Comment by PhantomGamers** [comment]
Thanks for this report, I have seen this issue in a few saves but had no idea how to reproduce it. This helps a lot!

**Comment by Nocturnal42** [comment]
It’s almost certainly lag related. Most of the time I’m playing from
Australia with a friend in the US.
