### ISSUE TITLE
Upgrade Universe exploration (4) perk doesn't work when the mod is activated

### ISSUE THREAD

**Issue by Caladcholg** [hubastard/nebula#497]
Hello,

In a game with only this mod and its dependencies activated, and the upgrade "Universe exploration (4)", it's impossible to view the resources from all planetary systems.
We have the same issue if we load a save in solo or multiplayer mode.

If we load the same save in vanilla, the perk works as intended.

**Comment by Ryefalk** [comment]
I have encountered the same issue.

**Comment by PhantomGamers** [comment]
this will be fixed in the next release
