### ISSUE TITLE
If there is building number change between server sends the factory and client loads, the objectId will desync

### ISSUE THREAD

**Issue by starfi5h** [hubastard/nebula#504]
It can be reproduced by the host building lots of stuff when the client is arriving on the planet in a high latency environment.
Nebula version 0.7.10 Game version 0.8.23.9989
![desync1](https://user-images.githubusercontent.com/50672801/149672467-2de1c312-c81f-4b42-be97-e8fa656cdf47.jpg)

The following user reports seem to cause by objectId desync too:
https://discord.com/channels/823320768086671421/858330101556183050/929740590357291129
https://discord.com/channels/823320768086671421/858330101556183050/931638752252682321

Maybe we can stop building changes on the planet before the client fully loads it to prevent this issue.

**Comment by sp00ktober** [comment]
could this cause #336 too?

**Comment by starfi5h** [comment]
I'm not sure. If it is caused by ``objId`` desync too, it should have more building connections errors than just inserters?
