### ISSUE TITLE
Update ILS code for 0.9.x game version

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#510]
Sort of a todo list for myself to keep track of what needs to be done for #506 .

- [x] Update reverse patch to work with the new version. its purpose is to update ship position and rendering clientside.
- [x] Update `StationComponent` ui to no have that register for syncing stuff but instead clients should request updates periodically while the ui is opened. changes should be requested to be done by host and propagated back to clients (just as building placement)
- [x] Sync `AddItem` calls in `InternalTickRemote` transpiler
- [x] Sync `TakeItem` calls in `InternalTickRemote` transpiler
- [x] Sync changes to storage beside tha above two calls in `InternalTickRemote` transpiler
- [x] Sync changes to `remoteOrder`
- [x] Sync energy usage of stations
- [x] Check if we should handle `workShipCount` and `idleShipCount` only on host or also on client.
- [x] Update `RematchRemotePairs` transpiler
- [x] Update the way we sync belt slot data

`RematchRemotePairs` does not fully work, clients can have a few ILS ships left rendered once a ILS is removed while having ships on their way.

**Comment by AlessandroPicoli** [comment]
Any idea when it will come out?

**Comment by sp00ktober** [comment]
Hard to say, im more or less half way through with my stuff on this.

**Comment by AlessandroPicoli** [comment]
I hope you can, I liked this mod more, congratulations for your work.

**Comment by sp00ktober** [comment]
For now you can downgrade your game version to 0.8 to play.
There were reports that loading saves from 0.9 on 0.8 game version breaks them so better make backups

**Comment by AlessandroPicoli** [comment]
oops managed to do it, cool that, congratulations

**Comment by m1ds** [comment]
Thank you for your awesome efforts!

**Comment by b4eb7** [comment]
I can't wait to use this mod

**Comment by AlessandroPicoli** [comment]
Oops the mod worked, I'm dying to play with a friend, but we're waiting for your mod, I hope you can do it. Tell the guys if you're on the right track. Thanks for your time spent making the mod.

**Comment by sp00ktober** [comment]
You can try out the pre release version found in the 0.9 pullrequest or on our discord server for now.
