### ISSUE TITLE
how to play with friends?

### ISSUE THREAD

**Issue by hkmrys** [hubastard/nebula#512]
How to download the online MOD of the beta version？

**Comment by hubastard** [comment]
You csn follow this guide: https://steamsplay.com/dyson-sphere-program-how-to-install-nebula-mod-via-mod-manager-guide/

That being said, you will need to install the game version 0.8.x since the mod does not support the new 0.9.x version yet.

**Comment by 2636337402** [comment]
> 您可以按照以下指南进行操作[：https://steamsplay.com/dyson-sphere-program-how-to-install-nebula-mod-via-mod-manager-guide/](https://steamsplay.com/dyson-sphere-program-how-to-install-nebula-mod-via-mod-manager-guide/)
> 
> 话虽如此，您需要安装游戏版本0.8.x，因为该mod尚不支持新的0.9.x版本。

Will mod be updated to the latest version
