### ISSUE TITLE
no multiplayer option

### ISSUE THREAD

**Issue by Nixitsumi** [hubastard/nebula#524]
dear developer,I've put Nebula0.8.1 in this directory:E:\steam\steamapps\common\Dyson Sphere Program\BepInEx\plugins, and update game to version 0.9.x,but i can not find multiplayer option in main menu,could you plz tell me how to solve this problem,best wish!

**Comment by csandazoltan** [comment]
Second it

**Comment by PhantomGamers** [comment]
Use the mod manager or manually download the dependencies mentioned on the thunderstore page

**Comment by csandazoltan** [comment]
> Use the mod manager or manually download the dependencies mentioned on the thunderstore page

I already had the previous version and the prerelase it worked, I just replaced the plugins content... Do I need anything more? Release notes hadn't mentioned anything
I don't want mod manager if i can install manually

**Comment by PhantomGamers** [comment]
you need all of the dependencies yes, they are viewable from the thunderstore page

**Comment by PhantomGamers** [comment]
![image](https://user-images.githubusercontent.com/844685/154562266-c56ca9ce-c6aa-4bd1-9a97-b3ffb6a94983.png)

**Comment by csandazoltan** [comment]
I yield

**Comment by PhantomGamers** [comment]
> I yield But i would ask to put a note in the installition guide that manual installition does not work anymore

it absolutely does work, you just have to download the dependencies as well. but that should be noted in the guide for sure

**Comment by PhantomGamers** [comment]
https://github.com/hubastard/nebula/wiki/Installing-a-pre-release-version has been updated with information about the required dependencies.

if this is too complicated than I highly recommend just using the mod manager which will automate the process
