### ISSUE TITLE
Cannot join when on another planet

### ISSUE THREAD

**Issue by GreenLightning** [hubastard/nebula#534]
We just updated from Nebula 0.8.2 to 0.8.3 and my friend was not able to join. On the host the game displays the player joining message and time is frozen and for the joining player the game hangs in the loading screen and has to be terminated using alt+f4. He tried multiple times and it didn't work. After I flew to the planet where he last logged off, he was able to join.

**Comment by starfi5h** [comment]
Do you use other mods besides Nebula dependencies, e.g. GalacticScale?

**Comment by starfi5h** [comment]
#533 is trying to fix the issue. Before the patch is done you may have to downgrade Nebula to 0.8.2 to run with GS2.

**Comment by GreenLightning** [comment]
Seems fixed with v0.8.4, thanks!
