### ISSUE TITLE
Possible to run in "headless"/"dedicated" mode?

### ISSUE THREAD

**Issue by CSchank** [hubastard/nebula#561]
I'm wondering if it's possible currently or perhaps in the future to run this mod as a sort of dedicated server instead of just from client-to-client? I understand this is asking a lot but I figured I'd ask nonetheless. Thanks!

**Comment by CSchank** [comment]
Edit: Oh wait, I just read the newest changelog and it looks like you just added this. Amazing!

**Comment by PhantomGamers** [comment]
See the instructions at the top: https://github.com/hubastard/nebula/pull/553
