### ISSUE TITLE
Can't even boot up the game

### ISSUE THREAD

**Issue by z9ctn4fn** [hubastard/nebula#572]
Just can't boot up the game. Just the mods needed and Nebula is properly installed, just when it boots up, it won't work

**Comment by starfi5h** [comment]
The game update today (0.9.26.13026) break Nebula 0.8.9.
If you want to play multiplayer before mod update, here are steps to revert game version to 0.9.26.12913:
1. open steam console (steam://nav/console)
2. enter `download_depot 1366540 1366541 5970550606738626023`
3. go to `Steam\steamapps\content\app_1366540\depot_1366541` and copy its content to `Steam\steamapps\common\Dyson Sphere Program`

**Comment by z9ctn4fn** [comment]
Thanks!
