### ISSUE TITLE
Information about the server in headless mode

### ISSUE THREAD

**Issue by davtur19** [hubastard/nebula#576]
Is there a way to find out the status of the server in headless mode, who's logged in, when it's saved, and things like that?

When I start the game as shown in the [guide](https://github.com/hubastard/nebula/wiki/Setup-Headless-Server), the game starts and runs, but I have no info about the game except from the task manager from which I see the process open.
Currently I don't have any windows open when I start the game with: `DSPGAME.exe -batchmode -nographics -server -load save1`

I saw that in [this video](https://streamable.com/gkp5o1) there is a console with some info, I don't understand if it's a bug or if I have to do something specific.

**Comment by PhantomGamers** [comment]
I have updated the wiki section with the information telling people to enable the BepInEx console. Thanks for the feedback! :)
