### ISSUE TITLE
[Nebula Error] Nebula Multiplayer Mod is incompatible (icw Bullettime 1.2.8

### ISSUE THREAD

**Issue by Tuumke** [hubastard/nebula#580]
```ini
An error has occurred! Game version 0.9.27.14546
Mods used: [IlLine1.0.0] [LDBTool2.0.6] [DSP Mod Save1.1.4] [DSP Common API1.5.4.0] [NebulaMultiplayerMod0.8.10.2] [NebulaMultiplayerModApi1.3.0.7] [BulletTime1.2.8] [Common API Nebula Compatibility1.5.4.0] 
[Nebula Error] Nebula Multiplayer Mod is incompatible
Unhandled exception occurred while patching the game.
```
After updating bullettime to 1.2.8

**Comment by Tuumke** [comment]
Not sure if you can link anything (no github guru) but also made one at bullettime:
https://github.com/starfi5h/DSP_Mod/issues/9

**Comment by Tuumke** [comment]
Hm looks more like it's an issue with Nebula and the current game version?

**Comment by starfi5h** [comment]
Yes. The game has been updated to 0.9.27.14546 and breaks Nebula.
If you still want to play currently, you can roll back the game to 0.9.26.13034, BulletTime to 1.2.7, and CommonAPI to 1.5.4.
To roll back, you can use Steam console command `download_depot 1366540  1366541 4636994869299211264` to download previous content.

**Comment by Tuumke** [comment]
Thanx
