### ISSUE TITLE
Git clone command wrong in wiki

### ISSUE THREAD

**Issue by Flapperkewiet** [hubastard/nebula#6]
In the wiki, on the "Setting up a decelopment environment" the git clone command says:

`git clone https://github.com/your-github-name/nebula.git --recursive`

while it should be:

`git clone https://github.com/hubastard/nebula.git --recursive`

**Comment by Flapperkewiet** [comment]
I was wrong, i somehow missed the "create a fork" step

**Comment by hubastard** [comment]
> I was wrong, i somehow missed the "create a fork" step

I also suggest you to pull the last commits since I refactored a lot of stuff.
