### ISSUE TITLE
Joining a game always respawn the landing pod for remote clients.

### ISSUE THREAD

**Issue by hubastard** [hubastard/nebula#60]
When a client joins a game where the landing pod is already destroyed, a landing pod is still created for the client the is joining the game.

**Comment by Baldie-dev** [comment]
I can take this one. So the goal is to generate a landing pod just once for the host player, right?

**Comment by hubastard** [comment]
The landing pod should be there for everyone in a new game. But once it's destroyed, any other player that joins should not see the pod.

**Comment by Baldie-dev** [comment]
I believe this can be closed since my fix #72  was already merged with master. :)
