### ISSUE TITLE
"Flip Whole Path" seems to desync players

### ISSUE THREAD

**Issue by TheL0ki** [hubastard/nebula#600]
The new "Flip Whole Path" feature seems to cause a desync as doing so is not reflected to other players and causes issues.

- Game Version: 0.9.27.15466
- Nebula Version: 0.8.12.0

**Comment by starfi5h** [comment]
Now fix with hotfix extension: NebulaCompatibilityAssist v0.1.11
https://dsp.thunderstore.io/package/starfi5h/NebulaCompatibilityAssist/
