### ISSUE TITLE
Add online multiplayer

### ISSUE THREAD

**Issue by BraveCaperCat2** [hubastard/nebula#603]
When will online multiplayer be added?
i want to play with my friend but port forwarding is complicated (we're not playing on the LAN and having to enter a password every time on our router isn't good) we DON'T use discord and we WILL NOT use it - ever - so please add online multiplayer like the Slime Rancher Multiplayer Mod does (Slime Rancher is another game)

**Comment by Zettexe** [comment]
Use something like Hamachi or Radmin VPN instead of port forwarding

**Comment by BraveCaperCat2** [comment]
i don't have any VPN's (i think i have express VPN on my computer but i haven't paid for it)

**Comment by BraveCaperCat2** [comment]
also i've done port fowarding before for minecraft but it would be easier (both for me and for others) if there was an online feature or server code.

**Comment by Zettexe** [comment]
Of course it's better to have integrated support proper but things can only move so fast and the contributors are doing their best. 
In the meantime you can use one of the programs I suggested, they are not like a typical VPN but allow you to connect to your friends as if you were on a LAN instead.

**Comment by PhantomGamers** [comment]
This mod already does, and always has, supported online multiplayer.

The discord integration in this mod has nothing to do with online connectivity and only serves to make inviting people easier.

Relay support that many other games use to eliminate the need for port forwarding or other NAT bypassing measures is unlikely to be implemented for the foreseeable future as the architecture of the base game is designed around a single player experience and thus the way in which we enable multiplayer support requires much more bandwidth than most other games and so relay options like Steam's, Epic's, and Discord's do not work very well with our approach.

The Hosting and Joining guide offers alternatives if port forwarding is not an option for you. https://github.com/hubastard/nebula/wiki/Hosting-and-Joining

**Comment by BraveCaperCat2** [comment]
and what i meant by online multiplayer didn't involve steam or epic or discord (i hate discord)
i meant something more like:
### Joining And Hosting:
1. Have all players open the game (after they have installed the mod)
2. Have the host open a game (or press host game)
3. fill in all the options for hosting the game
4. have the host send all the clients the "server code"
5. have the clients enter the "server code" in Join Game
6. Have Fun playing together

**Comment by BraveCaperCat2** [comment]
That's actually exactly how slime rancher's multiplayer mod works.
