### ISSUE TITLE
Mod cannot be installed:

### ISSUE THREAD

**Issue by BraveCaperCat2** [hubastard/nebula#604]
I wasn't even able to get the mod to work while i was questioning the hosting and joining tutorial (See: #603 for more info)
See these Screenshots:
![kVRPVNAwvl](https://user-images.githubusercontent.com/113925022/224686781-81d53c84-20ee-46ad-b88c-15bf0b228764.png)
![VVvZ9CCyvk](https://user-images.githubusercontent.com/113925022/224686825-7a651f59-f3ed-4ce3-8c41-ca0427cc7603.png)
![DSPGAME_CnEp5UYYoD](https://user-images.githubusercontent.com/113925022/224686851-85a6fa06-6c00-47eb-8780-0e586f4515bb.jpg)
that's my mod installation directory and DSP itself - plus the last one doesn't have the multiplayer menu that shows that installation completed.

if you need ANY more screenshots it's ok to ask me.

**Comment by PhantomGamers** [comment]
You possibly installed the wrong version of BepInEx. Make sure to follow the installation guide and install the correct version of BepInEx 5 https://github.com/hubastard/nebula/wiki/Installation

You also definitely installed commonapi incorrectly as you are missing the patcher folder.

If all else fails please use a mod manager as it will ensure that the installation proceeds correctly.

**Comment by BraveCaperCat2** [comment]
i'm quite sure i installed the version that the installation page links to.
but i'll try it anyway
also how do i install commonAPI correcctly

**Comment by BraveCaperCat2** [comment]
well i'm reinstalling the mods and BepInEx but can you tell me how to install CommonAPI Correctly?

**Comment by BraveCaperCat2** [comment]
wait no i looked at it's mod page and it has installation instructions.

**Comment by BraveCaperCat2** [comment]
this time i installed using the instructions on the website and it still didn't work.

**Comment by BraveCaperCat2** [comment]
are you going to say anything or what?

**Comment by starfi5h** [comment]
[Nebula Package(unzip on game folder).zip](https://github.com/hubastard/nebula/files/11114981/Nebula.Package.unzip.on.game.folder.zip)
This is an integrated package with BepInEx frame work and all the dependency mods. Unzip them on the game folder to install.
You can also install those mods yourself by following data structure in it.

**Comment by BraveCaperCat2** [comment]
Installing via the mod manager didn't work - although i DIDN'T uninstall the game first.

**Comment by starfi5h** [comment]
The above zip is for manually install.
For mod manager install and using ngrok to connect, check this video:
https://www.youtube.com/watch?v=FpbDUSNgHww

**Comment by BraveCaperCat2** [comment]
No, i used [this steam guide](https://steamcommunity.com/sharedfiles/filedetails/?id=2551456741) and a complete uninstall of the mod doesn't help

**Comment by BraveCaperCat2** [comment]
Wait, the mod manager was set to use the install on my other drive and i had just uninstalled the non-mod-manager mod on the default install location (for Steam) - Changing that to the default for steam fixed it! (but you should update that documentation)
