### ISSUE TITLE
[Headless-Server]run error

### ISSUE THREAD

**Issue by ByboyCn** [hubastard/nebula#610]
[Message:   BepInEx] BepInEx 5.4.22.0 - DSPGAME (2023/9/22 21:18:59)
[Info   :   BepInEx] Running under Unity v2018.4.12.5889476
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] Loaded 1 patcher method from [CommonAPIPreloader 1.5.7.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   BepInEx] Patching [Assembly-CSharp] with [CommonAPI.Preloader]
[Info   :Common API Preloader] Preloader patching is successful!
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 10 plugins to load
[Info   :   BepInEx] Loading [YurikoPlugin 1.0.7]
[Info   :   BepInEx] Loading [IlLine 1.0.0]
[Info   :   BepInEx] Loading [LDBTool 2.0.6]
[Info   :   LDBTool] LDBTool is loaded successfully!
[Info   :   BepInEx] Loading [DSP Mod Save 1.1.4]
[Info   :   BepInEx] Loading [DSP Common API 1.5.7.0]
[Info   :DSP Common API] Enabling CommonAPI Submodule: CustomKeyBindSystem
[Info   :DSP Common API] Enabling CommonAPI Submodule: PickerExtensionsSystem
[Info   :DSP Common API] Enabling CommonAPI Submodule: ProtoRegistry
[Info   :DSP Common API] Common API is initialized!
[Info   :   BepInEx] Loading [NebulaMultiplayerMod 0.8.14.3]
[Info   :NebulaMultiplayerMod] >> Initializing dedicated server
[Info   :NebulaMultiplayerMod] >> Creating new game (19940228, 64, 99.0)
[Info   :NebulaMultiplayerMod] Patching Dyson Sphere Program...
[Info   :NebulaMultiplayerMod] Applying patches from NebulaMultiplayerMod 0.8.14.0
[Info   :NebulaMultiplayerMod] Patching for headless mode...
[Info   :NebulaMultiplayerMod] Patching completed successfully
[Info   :NebulaMultiplayerMod] Applying Nebula behaviours..
[Info   :NebulaMultiplayerMod] Behaviours applied.
[Warning:NebulaMultiplayerMod] Discord.ResultException: InternalError
  at Discord.Discord..ctor (System.Int64 clientId, System.UInt64 flags) [0x00327] in <18ae93b5c15944ed8fb6bc40aa1d6b41>:IL_0327
  at NebulaWorld.SocialIntegration.DiscordManager.Setup (Discord.ActivityManager+ActivityJoinHandler activityJoinHandler) [0x00018] in <b7763e2d560a481c99af9671d828e483>:IL_0018
[Info   :   BepInEx] Loading [NebulaMultiplayerModApi 1.3.1.3]
[Info   :NebulaMultiplayerModApi] Nebula API is ready!
[Info   :   BepInEx] Loading [BulletTime 1.2.13]
[Info   :   BepInEx] Loading [PlanetMiner 3.0.8]
[Info   :   BepInEx] Loading [Common API Nebula Compatibility 1.5.7.0]
[Message:   BepInEx] Chainloader startup complete

He was stuck there for ten seconds, then forced the window to close
OS: winser 2019

**Comment by starfi5h** [comment]
It is required to let the Steam app run in the background, either in online mode or offline mode.

**Comment by ByboyCn** [comment]
3q
