### ISSUE TITLE
If two players connects at the same time, they will not see each other

### ISSUE THREAD

**Issue by Baldie-dev** [hubastard/nebula#63]
When two players connect at the same time, they will not see each other and the "Loading" message will freeze on the Host side:

![bug](https://i.imgur.com/NuYNudp.png)

**Comment by hubastard** [comment]
Yeah, we will need to make a pending player queue and make sure only send the PlayerSyncComplete packet once all the pending players are done loading.

**Comment by Mushroom** [comment]
I had this in mind when I created the "pendingPlayers" list during the handshake phase, so it should be easy to modify it to do as required
