### ISSUE TITLE
Factories are never unloaded

### ISSUE THREAD

**Issue by Mushroom** [hubastard/nebula#69]
Currently factories are requested as-needed from the host.

However, they are only ever loaded, and never unloaded, even if the player were to leave the system/planet.

Therefore, we need to implement a system to unload the factories when it is no longer required for a non-host player to have them loaded in. This can include cessation of events etc being sent/received once implemented.

**Comment by Baldie-dev** [comment]
Issue closed, since clients are now unloading factories
