### ISSUE TITLE
Game pause on the host is not synced with clients

### ISSUE THREAD

**Issue by Baldie-dev** [hubastard/nebula#81]
When the host pauses the game (by pressing ESC) the game tick will stop which causes desync on all clients, since their game tick will continue increasing. I think it is needed to sync the game pause or completely remove pausing the game when navigating to the menu.

**Comment by Baldie-dev** [comment]
I will take care of this:
- [ ] Prevent game pausing when players navigate to the menu (in progress)

**Comment by hubastard** [comment]
After merging the PR, I've notice that I don't really like this approach. Preventing the pause to occurs currently prevents the actual EscMenu from showing up, which prevents the players from exiting the game or from changing their game settings.
