### ISSUE TITLE
GameHistoryData Synchronization (research,recipes,bonuses,features)

### ISSUE THREAD

**Issue by Baldie-dev** [hubastard/nebula#87]
I am opening this issue for tracking purposes. I have started to work on this.
Basically, it is the synchronization of **GameHistoryData** class.

Progress:

- [x] Initial research synchronization (getting finished techs from the host)
- [x] Initial mecha stats/bonuses synchronization
- [x] Real-time research synchronization [progress - when player contribute to the research from the mech inventory]
- [x] Real-time research synchronization [unlocking of techs]
- [x] Sync of features (if sailing or warping is enabled / can design Dyson sphere)
- [x] Sync of available recipes
- [x] Sync of bonuses from techs
- [x] Sync of tech queue
- [x] Real-time sync of tech queue
- [x] Real-time sync of pausing and resuming tech queue
- [x] Sync of pinned stars / planets
- [ ] Real-time sync of star / planet pinning

**Comment by sp00ktober** [comment]
Sail/warp can be detected already by the effect sync code, or what do you use it for?

**Comment by Baldie-dev** [comment]
I meant the ability to do sail or to do warp. Since you have to unlock that feature by doing research.

**Comment by Baldie-dev** [comment]
And this is stored in the `public HashSet<int> featureKeys;` in the `GameHistoryData` which I believe is not being synchronized at the moment, right?

**Comment by sp00ktober** [comment]
As far as i know its not synced yet.

**Comment by Baldie-dev** [comment]
There is ongoing discussion regarding the **Real-time sync of star / planet pinning**, if it should be locally for each player or synchronized between all players.
