### ISSUE TITLE
sinking under the terrain bug

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#94]
https://user-images.githubusercontent.com/79335616/113276673-5c12d600-92e0-11eb-941d-465b7d5b3b73.mp4

Steps i did beofre this happened:
- client travels to the planet, then leaves again into space. (this way ``FactoryData`` is received and stored locally)
- host travels there, places building (not sure if its only triggered by ILS)
- client comes back, tadaa

This _may_ be caused by ``FlattenTerrain()`` which ic called when the building is placed.

**Comment by hubastard** [comment]
So this issue occurs because when we place a building the code calls a FlattenTerrain, but since we don't have the distant planet mesh that is being loaded, the ground collision that is generated in the FlattenTerrain is just an empty mesh (no collider at all)

**Comment by hubastard** [comment]
Right now, I can think of 2 ways of fixing this:
- We can try to find a way to call or replicate what the `PlanetModelingManager.RequestLoadPlanetFactory()` does to generate the planet mesh.
- We could also store all the FlattenTerrain operation that could not be perform on the host or on remote clients and request the list of FlattenTerrain operation that we have missed when we load the planet. We should also either save those operation to disk on the host or apply them all before closing the host game.

If anyone have a better idea please share your ideas 😄

**Comment by Baldie-dev** [comment]
Retested and seems to be closed

**Comment by aschmois** [comment]
By the way, I'm still seeing this exact problem pop up only for the host machine. I'm currently on EA 0.9.25.12201 Nebula 0.8.8.0, no extra mods installed. A restart to the main menu and back fixes the issue. I believe this problem happens when changing planets only.
